name: Identity
version: '${project.version}'
main: me.blunivers.identity.Identity
api-version: '1.21'
author: ShimonBlunivers

commands:
  identities:
    description: Command managing identities
    aliases:
      - ids
  idboard:
    description: Refreshes all scoreboards
  idstick:
    description: Gives you the Identity Stick
  infect:
    description: Infects player
  syringe:
    description: Gives player syringe
  cure:
    description: Cures the player
  idblocks:
    description: Opens enviromental block selector menu