name: Identity
version: '${project.version}'
main: me.blunivers.identity.Identity
api-version: '1.21'
author: ShimonBlunivers

commands:
  idstick:
    description: Gives you the Identity Stick
  idblocklist:
    description: Opens enviromental block selector menu
  jobs:
    description: Command managing jobs
    usage: /jobs [browse | info | join | progress | leave]
  refreshidentityscoreboard:
    description: Refreshes all scoreboards
  infect:
    description: Infects player
  syringe:
    description: Gives player syringe
  cure:
    description: Cures the player