name: Identity
version: '${project.version}'
main: me.blunivers.identity.Identity
api-version: '1.20'
author: ShimonBlunivers

commands:
  identities:
    description: Command managing identities
    aliases:
      - ids
    name: identities