name: Identity
version: '${project.version}'
main: me.blunivers.identity.Identity
api-version: '1.20'
author: ShimonBlunivers

commands:
  identities:
    description: Command managing identities
    aliases:
      - ids
    name: identities
  idboard:
    description: Refreshes all scoreboards
    name: idboard
  idstick:
    description: Gives you the Identity Stick
    name: idstick
  infect:
    description: Infects player
    name: infect
  syringe:
    description: Gives player syringe
    name: syringe
  cure:
    description: Cures the player
    name: cure